#
# Copyright 2020 Huawei Technologies Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

swagger: '2.0'
info:
  description: face_recognition
  version: 1.0.0
  title: face_recognition
  termsOfService: 'http://159.138.5.41:32100'
host: '127.0.0.1:9999'
basePath: /v1/face-recognition
schemes:
  - http
paths:
  /:
    get:
      tags:
        - FaceRecognition
      summary: healthCheck
      operationId: healthCheck
      description: healthCheck
      responses:
        '200':
          description: OK
          schema:
            type: string
  /upload:
    post:
      tags:
        - FaceRecognition
      summary: uploadImage
      operationId: uploadImage
      description: uploadImage
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          in: formData
          description: file to upload
          required: false
          type: file
      responses:
        '200':
          description: 文件上传成功
          schema:
            type: string
        '400':
          description: 上传失败
          schema:
            type: string
  /recognition:
    post:
      tags:
        - FaceRecognition
      summary: recognize
      operationId: recognize
      description: recognize
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          in: formData
          description: file to upload
          required: false
          type: file
      responses:
        '200':
          description: OK
          schema:
            type: string
  /video:
    post:
      tags:
        - FaceRecognition
      summary: video
      operationId: video
      description: video
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: video url
          required: true
          schema:
            $ref: '#/definitions/body'
      responses:
        '200':
          description: OK
          schema:
            type: string
definitions:
  body:
    type: object
    properties:
      url:
        type: string
